### ISSUE TITLE
Setup.py file contains odd commas

### ISSUE THREAD

**Issue by MaXal** [ScattPy/scikits.scattpy#6]
Setup.py contains odd commas:
MAINTAINER          = 'Alexander Vinokurov'
MAINTAINER_EMAIL    = 'scattpy@googlegroups.com'
...
It prevents from installation due to error:
Traceback (most recent call last):
  File "setup.py", line 79, in <module>
    'Topic :: Scientific/Engineering :: Astronomy', ])
  File "C:\Python27\lib\site-packages\numpy\distutils\core.py", line 186, in set
up
    return old_setup(**new_attr)
  File "C:\Python27\lib\distutils\core.py", line 152, in setup
    dist.run_commands()
  File "C:\Python27\lib\distutils\dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "C:\Python27\lib\distutils\dist.py", line 972, in run_command
    cmd_obj.run()
  File "C:\Python27\lib\site-packages\distribute-0.6.21-py2.7.egg\setuptools\com
mand\bdist_wininst.py", line 38, in run
    _bdist_wininst.run(self)
  File "C:\Python27\lib\distutils\command\bdist_wininst.py", line 185, in run
    self.create_exe(arcname, fullname, self.bitmap)
  File "C:\Python27\lib\site-packages\distribute-0.6.21-py2.7.egg\setuptools\com
mand\bdist_wininst.py", line 7, in create_exe
    _bdist_wininst.create_exe(self, arcname, fullname, bitmap)
  File "C:\Python27\lib\distutils\command\bdist_wininst.py", line 255, in create
_exe
    cfgdata = self.get_inidata()
  File "C:\Python27\lib\distutils\command\bdist_wininst.py", line 223, in get_in
idata
    (string.capitalize(name), escape(data)))
  File "C:\Python27\lib\distutils\command\bdist_wininst.py", line 216, in escape

```
return string.replace(s, "\n", "\\n")
```

  File "C:\Python27\lib\string.py", line 519, in replace
    return s.replace(old, new, maxreplace)
AttributeError: 'tuple' object has no attribute 'replace'

Suggested fix:
Remove unnecessary commas.

**Comment by MaXal** [comment]
Close as duplicate.
